---

- name: Install Homebrew using git clone
  hosts: all
  become: yes
  gather_facts: yes


  tasks:
  - name: Clone Homebrew git repository
    git:
      repo: https://github.com/Homebrew/brew.git
      dest: /usr/local/Homebrew
      update: yes

 
  - name: Set Homebrew environment variables
    blockinfile:
      path: /Users/tradmin/.bash_profile
      block: |
          # Homebrew 
          export PATH="/usr/local/Homebrew/bin:$PATH"

  
  - name: Install Homebrew packages
    homebrew:
      name:
        - wget
        - python
        - ansible


