---

- name: Install Homebrew on M1 Mac with Zsh shell
  hosts: localhost
  become: yes

  tasks:
    - name: Install Homebrew
      shell: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/tradmin/.zprofile
      args:
        executable: /bin/zsh
      environment:
        PATH: "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

    - name: Update Homebrew and installed packages
      shell: |
        /opt/homebrew/bin/brew update
        /opt/homebrew/bin/brew upgrade
      args:
        executable: /bin/zsh

