---
- name: win_chocolatey module demo
  hosts: windows
  become: false
  gather_facts: false
  vars:
    - packages:
      - git
      - notepadplusplus
      - skype
  tasks:
    - name: install packages
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ packages }}"
        state: present
